name: demo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.4

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_logo.png
  android: true
  ios: false
  fullscreen: true

android_12:
  color: "#ffffff"
  image: assets/splash_logo.png

# âœ… ONLY REQUIRED ADDITION FOR APP ICON (nothing else changed)
flutter_icons:
  android: true
  ios: false
  image_path: assets/icon/app_icon.png
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/splash_logo.png
    - assets/icon/app_icon.png
